# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='goles_local',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='goles_visitante',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
