# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0003_partidopendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Victorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victorias_local', models.IntegerField()),
                ('empates_local', models.IntegerField()),
                ('derrotas_local', models.IntegerField()),
                ('victorias_visitante', models.IntegerField()),
                ('empates_visitante', models.IntegerField()),
                ('derrotas_visitante', models.IntegerField()),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultados.Equipo')),
            ],
        ),
    ]
