# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0006_auto_20170509_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victorias',
            name='id',
        ),
        migrations.AlterField(
            model_name='victorias',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='resultados.Equipo'),
        ),
    ]
